CMR-8087: Adds collection level holdings API endpoint
nasa/cmr-opensearch pull request #96
Opened 2022-07-22 17:01 UTC by abbottry

2022-07-25 16:02 UTC, ygliuvt requested changes
A brief description of this new endpoint should be added to the Opensearch documentation page or at least the README.

2022-07-25 18:02 UTC, ygliuvt approved these changes

2022-07-26 12:28 UTC, eereiter approved these changes

2022-07-26 13:13 UTC, merged

2022-07-28 19:26 UTC, jceaser commented on Gemfile.lock
> +    libv8 (3.16.14.19-x86_64-darwin-18)
does this mean that the code only works on a mac? because the deploy is failing now